/* 7H Prompter — beat kits. Drum language is the load-bearing layer. */
window.BEAT_FAMILIES = [
  { id: "hiphop", name: "Hip-Hop", blurb: "Boom bap to rage. Rapper-ready pockets." },
  { id: "rnb", name: "R&B", blurb: "Slow jams, neo-soul, trap-soul." },
  { id: "dancehall", name: "Dancehall", blurb: "Riddims. Toast-ready. Snare on 3." },
  { id: "afro", name: "Afrobeats", blurb: "Lagos to Joburg. Percussion first." },
  { id: "club", name: "Club", blurb: "Amapiano, gqom, garage, baile, dembow." },
  { id: "more", name: "More", blurb: "Phonk, drill, lofi, dnb, house." }
];

window.BEAT_KITS = [
  /* ───────── HIP-HOP ───────── */
  {
    id: "boom-bap",
    family: "hiphop",
    name: "90s Boom Bap",
    region: "East Coast",
    era: "1993–1998",
    bpm: [88, 96],
    defaultBpm: 92,
    key: "Cmin",
    drumIdentity: "boom-bap",
    genre: "90s boom-bap hip-hop instrumental beat",
    mood: "gritty, laid-back, street-wise",
    kick: "punchy sampled acoustic kick on 1 and the and-of-2",
    snare: "cracking snare on 2 and 4, slight swing",
    hats: "dusty swung 16th hi-hats, closed, dry",
    perc: "light vinyl scratch fills, occasional shaker",
    bass: "warm round bassline locked under the kick, no 808 slides",
    melody: "chopped dusty soul sample loop, short chops",
    texture: "vinyl crackle, tape hiss, dry unquantized drums, MPC swing",
    compactExtra: "dusty soul chops, MPC swing",
    intro: "vinyl crackle, filtered sample fade-in, kick count-in",
    verse: "full boom-bap pocket, bass locked, sample loop, empty space for a rapper",
    hook: "sample opens up, extra snare layer, short scratch fill",
    brk: "drums drop to kick and snare only, sample filtered down",
    drop: "full drums slam back, bass thicker, sample dry",
    outro: "sample filters out, vinyl crackle, snare tail",
    exclude: ["vocals", "singing", "rapping", "choir", "spoken word", "ad-libs", "808 slides", "trap hi-hats"],
    names: ["DUST POCKET", "BROWN BAG", "IRON GATE", "SPIT CUP"]
  },
  {
    id: "sample-chop",
    family: "hiphop",
    name: "Sample Chop",
    region: "East Coast / Underground",
    era: "1996–2004",
    bpm: [84, 94],
    defaultBpm: 89,
    key: "Dmin",
    drumIdentity: "swung boom-bap",
    genre: "underground hip-hop instrumental beat, sample-based",
    mood: "moody, cinematic, late-night",
    kick: "round kick with short decay, syncopated",
    snare: "snappy snare on 2 and 4 plus ghost notes",
    hats: "sparse hats, more air than pattern",
    perc: "rim clicks, vinyl rewind",
    bass: "simple two-note bass, heavy and slow",
    melody: "obscure jazz-loop chops, pitched down, chopped on the 1",
    texture: "low-pass filter, analog grit, headroom, not loud",
    compactExtra: "jazz chops, ghost snares",
    intro: "pitched sample alone, no drums",
    verse: "drums enter thin, lots of empty bars for bars",
    hook: "sample layers, extra kick, still no melody competing with a rapper",
    brk: "drums out, chopped vocal-less horn stab",
    drop: "pocket returns, bass louder",
    outro: "tape stop, sample dies",
    exclude: ["vocals", "singing", "rapping", "choir", "trap hats", "EDM"],
    names: ["NIGHT CHOP", "LOW PASS", "ASH LOOP", "THIRD RAIL"]
  },
  {
    id: "atl-trap",
    family: "hiphop",
    name: "Atlanta Trap",
    region: "Atlanta",
    era: "2016–2024",
    bpm: [130, 150],
    defaultBpm: 140,
    key: "Fmin",
    drumIdentity: "half-time trap",
    genre: "hard-hitting Atlanta trap instrumental beat",
    mood: "dark, menacing, spacious",
    kick: "tight punchy kick layered under 808",
    snare: "sharp snare/clap on beat 3 of the half-time grid",
    hats: "fast rolling 16th and 32nd hi-hats with triplet rolls",
    perc: "open hat on offbeats, sparse perc",
    bass: "distorted 808 sub with long sustain and pitch slides",
    melody: "dark minor-key pluck or piano, sparse, lots of empty space",
    texture: "modern digital mix, heavy low end, dark atmosphere, deliberate silence",
    compactExtra: "808 slides, triplet hats, snare on 3",
    intro: "atmosphere pad, 808 tail, no full drums yet",
    verse: "half-time trap pocket, 808 slides, hats rolling, melody sparse",
    hook: "hats busier, 808 more aggressive, melody hook repeats",
    brk: "drums cut, 808 held, reverse crash",
    drop: "full trap drums slam, 808 max",
    outro: "808 decay, hats stop, pad remains",
    exclude: ["vocals", "singing", "rapping", "choir", "acoustic drums", "guitar solo"],
    names: ["WET 808", "NIGHT SLIDE", "TRAP HOLE", "BLACK ICE"]
  },
  {
    id: "melodic-trap",
    family: "hiphop",
    name: "Melodic Trap",
    region: "Atlanta / Internet",
    era: "2018–2025",
    bpm: [136, 152],
    defaultBpm: 144,
    key: "Amin",
    drumIdentity: "half-time trap",
    genre: "melodic trap instrumental beat",
    mood: "emotional, dark-sweet, cinematic",
    kick: "punchy kick under 808",
    snare: "crisp snare on 3, layered clap",
    hats: "rolling hats with open-hat lifts into the snare",
    perc: "subtle shaker, reverse FX",
    bass: "clean 808 with pitch melody, not just slides",
    melody: "sad guitar or bell melody, repeating 4-bar hook",
    texture: "wide reverb on melody, dry drums, modern polish",
    compactExtra: "sad melody, 808, snare on 3",
    intro: "melody alone with reverb",
    verse: "drums half-time, melody quieter, space for a rapper",
    hook: "melody full, extra clap, 808 sings",
    brk: "melody + 808 only",
    drop: "full beat, hats denser",
    outro: "melody delay trails off",
    exclude: ["vocals", "singing", "rapping", "choir", "spoken word"],
    names: ["GLASS 144", "SAD PLUCK", "BLUE SLIDE", "NIGHT BELL"]
  },
  {
    id: "uk-drill",
    family: "hiphop",
    name: "UK Drill",
    region: "South London",
    era: "2018–2024",
    bpm: [138, 145],
    defaultBpm: 142,
    key: "Dmin",
    drumIdentity: "UK drill",
    genre: "UK drill instrumental beat",
    mood: "cold, menacing, street",
    kick: "tight kick, syncopated, not four-on-the-floor",
    snare: "syncopated snare pattern, not only on 3, extra late snares",
    hats: "straight 16ths switching into triplet rolls",
    perc: "rim and click, sparse",
    bass: "sliding 808 with aggressive downward pitch bends",
    melody: "minor piano or strings, plate reverb, ominous stabs on 2 and 4",
    texture: "cold mix, dry drums, distant piano, estate-block atmosphere",
    compactExtra: "sliding 808, syncopated snare, cold piano",
    intro: "piano motif, no drums",
    verse: "UK drill pocket, sliding 808, syncopated snares",
    hook: "string stab, busier hats, 808 meaner",
    brk: "piano only, reversed cymbal",
    drop: "full drill drums, 808 dives",
    outro: "piano decays, 808 stops dead",
    exclude: ["vocals", "singing", "rapping", "choir", "US trap bounce", "happy"],
    names: ["ENDS 142", "COLD SLIDE", "BLOCK PIANO", "GREY 808"]
  },
  {
    id: "ny-drill",
    family: "hiphop",
    name: "NY Drill",
    region: "Brooklyn / Bronx",
    era: "2020–2024",
    bpm: [140, 146],
    defaultBpm: 143,
    key: "Cmin",
    drumIdentity: "NY drill",
    genre: "New York drill instrumental beat",
    mood: "aggressive, grimy, urgent",
    kick: "hard kick, more on-grid than UK",
    snare: "loud snare on 3 plus extra flams",
    hats: "busy hats, rapid rolls into snare",
    perc: "gun-click perc, metal ticks",
    bass: "distorted sliding 808, shorter than UK",
    melody: "dark piano loop or flute, repetitive",
    texture: "loud, clipped, street, less space than UK drill",
    compactExtra: "loud snare, distorted 808, dark piano",
    intro: "piano loop, riser",
    verse: "NY drill drums, 808 slides, tight pocket",
    hook: "flute or piano hook, extra snare",
    brk: "drums halt, 808 hum",
    drop: "full drums, distortion up",
    outro: "hard stop, no fade",
    exclude: ["vocals", "singing", "rapping", "choir", "soft"],
    names: ["BX SLIDE", "FLAM 143", "BLOCK HEAT", "STEEL LOOP"]
  },
  {
    id: "g-funk",
    family: "hiphop",
    name: "G-Funk",
    region: "West Coast",
    era: "1993–1998",
    bpm: [90, 102],
    defaultBpm: 96,
    key: "Gmin",
    drumIdentity: "laid-back west coast",
    genre: "90s west coast G-funk instrumental beat",
    mood: "laid-back, funky, cruise",
    kick: "round deep kick on 1 and 3",
    snare: "fat snare on 2 and 4, slight delay",
    hats: "open funky hats, not trap rolls",
    perc: "cowbell optional, conga ghost",
    bass: "deep funky synth bass, minimoog-style, sliding",
    melody: "whiny high synth lead, talk-box tone without vocals, Rhodes stabs",
    texture: "warm analog, California sun, slightly dirty mix",
    compactExtra: "whiny synth lead, funky bass, laid-back drums",
    intro: "synth lead lick, no drums",
    verse: "west coast pocket, bass groove, lead in the gaps",
    hook: "lead synth full, extra hats",
    brk: "bass and kick only",
    drop: "full G-funk arrangement",
    outro: "lead delays out, sunset fade",
    exclude: ["vocals", "singing", "rapping", "choir", "trap hats", "talk box singing"],
    names: ["SUNSET 96", "LOWRIDE", "WHINE LEAD", "PALM 808"]
  },
  {
    id: "crunk",
    family: "hiphop",
    name: "Crunk / Dirty South",
    region: "Memphis / Atlanta",
    era: "2003–2008",
    bpm: [70, 82],
    defaultBpm: 76,
    key: "Emin",
    drumIdentity: "slow crunk",
    genre: "dirty south crunk instrumental beat",
    mood: "aggressive, hypnotic, club",
    kick: "huge 808 kick on every downbeat",
    snare: "loud snare/clap on 2 and 4, or on 3 in slow feel",
    hats: "simple 8th hats, not busy",
    perc: "cowbell, orchestra hit, crowd-less",
    bass: "overdriven 808 that is the kick",
    melody: "dark synth stab loop, repetitive, menacing",
    texture: "loud, simple, hypnotic, club PA",
    compactExtra: "huge 808, orchestra stabs, slow",
    intro: "synth stab, 808 pulse",
    verse: "minimal crunk pocket, space for chants but no vocals generated",
    hook: "orchestra hit, snare louder",
    brk: "808 only",
    drop: "full stabs + drums",
    outro: "808 fade",
    exclude: ["vocals", "singing", "rapping", "choir", "chanting", "crowd vocals"],
    names: ["CLUB 76", "ORCH HIT", "SLOW BANG", "TRUNK"]
  },
  {
    id: "rage",
    family: "hiphop",
    name: "Rage / Opium",
    region: "Internet",
    era: "2021–2026",
    bpm: [140, 160],
    defaultBpm: 148,
    key: "F#min",
    drumIdentity: "rage 808",
    genre: "rage hip-hop instrumental beat, opium-style",
    mood: "distorted, frantic, underground",
    kick: "clicky kick under blown-out 808",
    snare: "thin snare on 3, sometimes skipped",
    hats: "fast, glitchy, sometimes missing",
    perc: "industrial ticks, laser perc",
    bass: "heavily distorted 808, mid-range growl",
    melody: "detuned synth lead, screaming but instrumental, no voice",
    texture: "overdriven, club, lo-fi digital clip, dark",
    compactExtra: "distorted 808, detuned lead, rage drums",
    intro: "distorted lead, no drums",
    verse: "rage pocket, 808 growl, spacey",
    hook: "lead full, drums glitchier",
    brk: "silence then 808",
    drop: "max distortion",
    outro: "hard cut",
    exclude: ["vocals", "singing", "rapping", "choir", "clean mix", "acoustic"],
    names: ["CLIP 148", "OPIUM LEAD", "RED 808", "STATIC"]
  },
  {
    id: "lofi-hop",
    family: "hiphop",
    name: "Lo-fi Hip-Hop",
    region: "Internet",
    era: "2016–2024",
    bpm: [70, 86],
    defaultBpm: 82,
    key: "Bbmaj",
    drumIdentity: "dusty boom-bap",
    genre: "lo-fi hip-hop instrumental beat",
    mood: "mellow, hazy, late-night study",
    kick: "soft kick, rounded, low click",
    snare: "muted snare on 2 and 4",
    hats: "soft swung hats",
    perc: "vinyl pops",
    bass: "upright or soft sub, sidechained gently",
    melody: "detuned Rhodes or jazz piano loop",
    texture: "vinyl crackle, tape hiss, rainy, seamless loop feel",
    compactExtra: "Rhodes, vinyl, dusty drums",
    intro: "crackle + Rhodes",
    verse: "full lofi pocket, loopable",
    hook: "piano variation, same drums",
    brk: "bass and crackle",
    drop: "drums return soft",
    outro: "no fade-out if loop, else crackle remains",
    exclude: ["vocals", "singing", "rapping", "choir", "loud 808", "trap hats"],
    names: ["RAIN 82", "DUST KEYS", "NIGHT DESK", "WARM TAPE"]
  },

  /* ───────── R&B ───────── */
  {
    id: "quiet-storm",
    family: "rnb",
    name: "Quiet Storm",
    region: "US",
    era: "1987–1994",
    bpm: [60, 76],
    defaultBpm: 68,
    key: "Amin",
    drumIdentity: "slow R&B",
    genre: "90s quiet-storm R&B instrumental beat",
    mood: "sensual, late-night, warm",
    kick: "soft kick on 1, gentle",
    snare: "snare or rim on 2 and 4, lots of ghost notes",
    hats: "closed hats with finger snaps",
    perc: "soft shaker",
    bass: "warm electric bass, melodic, in the pocket",
    melody: "Rhodes and silky synth pad, clean guitar fills",
    texture: "analog warmth, bedroom, slow",
    compactExtra: "Rhodes, finger snaps, warm bass",
    intro: "Rhodes chords, no drums",
    verse: "slow R&B pocket, bass walking gently, empty for a singer but no vocals generated",
    hook: "pad opens, guitar fill, drums fuller",
    brk: "Rhodes + bass",
    drop: "full quiet-storm groove",
    outro: "pad fade",
    exclude: ["vocals", "singing", "rapping", "choir", "trap", "harsh 808"],
    names: ["LOW LIGHT", "SILK 68", "AFTER HOURS", "WARM KEY"]
  },
  {
    id: "new-jack",
    family: "rnb",
    name: "New Jack Swing",
    region: "US",
    era: "1988–1993",
    bpm: [96, 112],
    defaultBpm: 104,
    key: "Cmin",
    drumIdentity: "swung new-jack",
    genre: "new jack swing instrumental beat",
    mood: "bouncy, funky, confident",
    kick: "punchy swing kick, syncopated",
    snare: "fat snare on 2 and 4 with swung ghost notes",
    hats: "swung 16ths, busy but groovy",
    perc: "handclaps, cowbell light",
    bass: "funky synth bass, staccato",
    melody: "stabs, bell synth, chopped horn hits, no singing",
    texture: "dry 90s drum machine, Teddy-Riley-era swing without naming artists",
    compactExtra: "swung drums, synth bass, claps",
    intro: "drum machine count-in",
    verse: "new jack pocket, bass popping",
    hook: "horn stabs, extra claps",
    brk: "drums + bass",
    drop: "full swing",
    outro: "drum fill end",
    exclude: ["vocals", "singing", "rapping", "choir", "modern trap"],
    names: ["SWING 104", "BELL STAB", "JACK POCKET", "CLAP 90"]
  },
  {
    id: "neo-soul",
    family: "rnb",
    name: "Neo-Soul",
    region: "US / UK",
    era: "1999–2006",
    bpm: [84, 96],
    defaultBpm: 90,
    key: "Emin",
    drumIdentity: "live neo-soul pocket",
    genre: "neo-soul instrumental beat",
    mood: "warm, groovy, intimate",
    kick: "live kick with ghost, behind the beat",
    snare: "crisp snare with ghost notes, human",
    hats: "live hats, slightly open",
    perc: "shaker, conga ghost",
    bass: "deep electric bass, melodic, D'Angelo-pocket described as behind-the-beat bass",
    melody: "Rhodes with tremolo, muted wah guitar, no vocals",
    texture: "vinyl analog, live room, imperfect timing",
    compactExtra: "Rhodes, wah guitar, live pocket",
    intro: "Rhodes + bass",
    verse: "full neo-soul groove, drums humanized",
    hook: "guitar wah, extra perc",
    brk: "bass breakdown",
    drop: "full band pocket",
    outro: "Rhodes tremolo fade",
    exclude: ["vocals", "singing", "rapping", "choir", "trap hats", "quantized EDM"],
    names: ["BEHIND 90", "WAH DUST", "BROWN SUGAR", "LIVE POCKET"]
  },
  {
    id: "dark-rnb",
    family: "rnb",
    name: "Dark Alt R&B",
    region: "Toronto / Internet",
    era: "2012–2024",
    bpm: [70, 90],
    defaultBpm: 80,
    key: "Fmin",
    drumIdentity: "minimal dark R&B",
    genre: "dark alternative R&B instrumental beat",
    mood: "moody, sensual, nocturnal",
    kick: "deep kick, sparse",
    snare: "snappy snare or clap on 3, half-time feel",
    hats: "minimal hats, some 808-style ticks",
    perc: "atmosphere hits",
    bass: "sub-bass drone with slow movement",
    melody: "minor keys, icy synth, distant guitar",
    texture: "reverb, night drive, spacious, modern",
    compactExtra: "sub bass, icy synth, half-time snare",
    intro: "pad and sub",
    verse: "minimal dark pocket, space for a singer, no vocals",
    hook: "melody more present, snare heavier",
    brk: "atmosphere only",
    drop: "full dark R&B beat",
    outro: "reverb wash",
    exclude: ["vocals", "singing", "rapping", "choir", "bright pop", "acoustic guitar strum"],
    names: ["NIGHT 80", "ICE SUB", "XO KEYS", "BLACK SILK"]
  },
  {
    id: "trap-soul",
    family: "rnb",
    name: "Trap Soul",
    region: "US",
    era: "2015–2024",
    bpm: [120, 140],
    defaultBpm: 130,
    key: "Cmin",
    drumIdentity: "half-time trap-soul",
    genre: "trap-soul R&B instrumental beat",
    mood: "emotional, smooth, modern",
    kick: "soft kick under 808",
    snare: "snare on 3, layered with snap",
    hats: "light rolling hats, not aggressive",
    perc: "finger snaps",
    bass: "clean 808, melodic, less distortion",
    melody: "soul chords on keys, guitar licks",
    texture: "polished, wet vocals-space, dry drums",
    compactExtra: "808, soul chords, snare on 3",
    intro: "chords + 808",
    verse: "trap-soul pocket, room for melody singing but generate no vocals",
    hook: "chords brighter, hats lift",
    brk: "chords only",
    drop: "full trap-soul drums",
    outro: "808 + keys fade",
    exclude: ["vocals", "singing", "rapping", "choir", "harsh distortion"],
    names: ["SOUL 130", "SNAP 3", "WET KEYS", "SOFT 808"]
  },
  {
    id: "slow-jam",
    family: "rnb",
    name: "90s Slow Jam",
    region: "US",
    era: "1994–1999",
    bpm: [62, 78],
    defaultBpm: 72,
    key: "Dmin",
    drumIdentity: "slow jam",
    genre: "90s slow-jam R&B instrumental beat",
    mood: "romantic, lush, late-night",
    kick: "soft deep kick",
    snare: "fat snare on 2 and 4, lots of ghosts",
    hats: "16th hats, silky",
    perc: "finger snaps, light conga",
    bass: "smooth bass guitar",
    melody: "lush pads, electric piano, quiet guitar",
    texture: "90s R&B mix, wide, warm",
    compactExtra: "lush pads, snaps, slow jam drums",
    intro: "pad swell",
    verse: "slow jam pocket",
    hook: "melody lift, extra snaps",
    brk: "piano + bass",
    drop: "full lush groove",
    outro: "pad fade",
    exclude: ["vocals", "singing", "rapping", "choir", "trap", "EDM"],
    names: ["CANDLE 72", "LUSH 90", "SLOW BURN", "SILK SNARE"]
  },
  {
    id: "bedroom-rnb",
    family: "rnb",
    name: "Bedroom R&B",
    region: "Internet",
    era: "2018–2026",
    bpm: [78, 98],
    defaultBpm: 88,
    key: "Gmin",
    drumIdentity: "soft trap-R&B",
    genre: "bedroom R&B instrumental beat",
    mood: "intimate, hazy, DIY-luxe",
    kick: "soft 808 kick",
    snare: "light snare, sometimes clap",
    hats: "soft closed hats",
    perc: "clicks",
    bass: "round 808, quiet",
    melody: "detuned keys, guitar fragment",
    texture: "close-mic, tape, not stadium",
    compactExtra: "soft 808, detuned keys, intimate",
    intro: "keys lo-fi",
    verse: "bedroom pocket",
    hook: "guitar fragment, drums a bit bigger",
    brk: "keys only",
    drop: "full soft beat",
    outro: "tape stop",
    exclude: ["vocals", "singing", "rapping", "choir", "festival EDM"],
    names: ["ROOM 88", "TAPE KEY", "SOFT CLIP", "HAZY 808"]
  },

  /* ───────── DANCEHALL ───────── */
  {
    id: "digital-riddim",
    family: "dancehall",
    name: "Digital Riddim",
    region: "Kingston",
    era: "1985–1994",
    bpm: [90, 100],
    defaultBpm: 95,
    key: "Cmin",
    drumIdentity: "digital dancehall, snare on 3",
    genre: "classic digital dancehall riddim instrumental",
    mood: "raw, hypnotic, yard",
    kick: "heavy electronic kick on 1, sometimes 1 and the and-of-2",
    snare: "snappy snare or rimshot landing on beat 3, the dancehall backbone",
    hats: "shuffling closed hats, not trap rolls",
    perc: "rim, light syndrum",
    bass: "deep square digital bass, simple and heavy, on the downbeats",
    melody: "Casio-style synth stab, sparse, riddim not a song",
    texture: "80s digital, dry, Kingston sound system, toast-ready",
    compactExtra: "snare on 3, digital bass, riddim",
    intro: "bass + kick, no snare yet",
    verse: "full digital riddim, snare on 3, empty for a toaster, no vocals",
    hook: "synth stab every 4 bars, drums unchanged",
    brk: "bass and kick only, snare drops",
    drop: "snare returns on 3, full riddim",
    outro: "bass loop, hard stop",
    exclude: ["vocals", "singing", "rapping", "toasting", "choir", "spoken word", "ad-libs", "trap hi-hats"],
    names: ["SLENG 95", "YARD BOX", "RIM 3", "DIGI BASS"]
  },
  {
    id: "bashment",
    family: "dancehall",
    name: "Modern Bashment",
    region: "Kingston / London",
    era: "2012–2026",
    bpm: [98, 108],
    defaultBpm: 102,
    key: "Fmin",
    drumIdentity: "modern dancehall, snare on 3",
    genre: "modern dancehall bashment instrumental riddim",
    mood: "aggressive, dancefloor, sweaty",
    kick: "punchy kick on 1 and syncopated pickups",
    snare: "loud snappy snare on 3, sometimes extra flam",
    hats: "busy shuffling hats, modern",
    perc: "timbale fills, cowbell light",
    bass: "deep sliding bass, dancehall not trap-808, still heavy sub",
    melody: "sparse synth horn or flute stab, offbeat guitar skank",
    texture: "modern club mix, toast-ready, no melody hogging the pocket",
    compactExtra: "snare on 3, sliding bass, guitar skank",
    intro: "skank guitar + bass",
    verse: "bashment pocket, snare on 3, space for toasting, generate no vocals",
    hook: "synth stab hook, drums hotter",
    brk: "drums drop, bass keeps going",
    drop: "full bashment slam",
    outro: "snare roll into stop",
    exclude: ["vocals", "singing", "rapping", "toasting", "choir", "spoken word", "ad-libs"],
    names: ["WET 102", "BASH 3", "SKANK SUB", "YARD HEAT"]
  },
  {
    id: "one-drop-dh",
    family: "dancehall",
    name: "One-Drop Hybrid",
    region: "Jamaica",
    era: "1978–1988",
    bpm: [78, 90],
    defaultBpm: 84,
    key: "Gmin",
    drumIdentity: "one-drop",
    genre: "reggae-dancehall one-drop instrumental riddim",
    mood: "heavy, meditative, roots",
    kick: "kick together with snare on beat 3, little kick on 1",
    snare: "rimshot on 3, the one-drop",
    hats: "open hats on offbeats, skank feel",
    perc: "nyabinghi-ish kette light, shaker",
    bass: "deep round bass guitar, slow and hypnotic",
    melody: "offbeat guitar skank, organ bubble, melodica optional",
    texture: "spring reverb, analog, Kingston 80s",
    compactExtra: "one-drop, skank guitar, deep bass",
    intro: "organ + bass",
    verse: "one-drop pocket, bass heavy",
    hook: "melodica line, still instrumental",
    brk: "dub: drums drop, bass + delay",
    drop: "full one-drop returns",
    outro: "dub delay fade",
    exclude: ["vocals", "singing", "rapping", "toasting", "choir", "trap", "four-on-the-floor"],
    names: ["DROP 84", "SKANK DUB", "RIM ROOTS", "STEPPER"]
  },
  {
    id: "wine",
    family: "dancehall",
    name: "Slow Wine",
    region: "Jamaica / Caribbean",
    era: "2008–2020",
    bpm: [88, 96],
    defaultBpm: 92,
    key: "Amin",
    drumIdentity: "slow dancehall wine",
    genre: "slow wine dancehall instrumental riddim",
    mood: "sensual, heavy, night",
    kick: "fat kick on 1, space after",
    snare: "snare on 3, fat not thin",
    hats: "simple shuffle",
    perc: "sparse",
    bass: "very deep slow bass, almost a hum",
    melody: "minor synth, airy, not busy",
    texture: "dark club, body-tempo, toast-ready",
    compactExtra: "slow snare on 3, deep bass, wine tempo",
    intro: "bass hum",
    verse: "slow wine pocket",
    hook: "synth air, drums same",
    brk: "bass only",
    drop: "snare back on 3",
    outro: "bass fade",
    exclude: ["vocals", "singing", "toasting", "choir", "fast hats", "EDM"],
    names: ["WINE 92", "LOW HUM", "NIGHT 3", "SLOW YARD"]
  },
  {
    id: "dh-trap",
    family: "dancehall",
    name: "Dancehall Trap",
    region: "Kingston / Atlanta",
    era: "2016–2025",
    bpm: [95, 110],
    defaultBpm: 100,
    key: "Dmin",
    drumIdentity: "dancehall-trap hybrid",
    genre: "dancehall-trap fusion instrumental beat",
    mood: "dark, bouncy, modern",
    kick: "808 kick with dancehall placement on 1",
    snare: "snare on 3, trap clap layered",
    hats: "some trap rolls but keep dancehall shuffle as the grid",
    perc: "rimshots",
    bass: "808 slides inside a dancehall bass rhythm",
    melody: "dark pluck, sparse",
    texture: "modern, club, crossover",
    compactExtra: "snare on 3, 808 slides, dancehall grid",
    intro: "808 + pad",
    verse: "hybrid pocket, still snare on 3",
    hook: "hats roll, bass slides",
    brk: "808 only",
    drop: "full hybrid",
    outro: "hard stop",
    exclude: ["vocals", "singing", "toasting", "rapping", "choir"],
    names: ["GRID 100", "YARD 808", "HYBRID 3", "SLIDE SKANK"]
  },
  {
    id: "island-pop",
    family: "dancehall",
    name: "Island Pop Riddim",
    region: "Caribbean",
    era: "2017–2026",
    bpm: [96, 106],
    defaultBpm: 100,
    key: "Cmaj",
    drumIdentity: "pop dancehall",
    genre: "island-pop dancehall instrumental riddim",
    mood: "bright, danceable, summer",
    kick: "punchy kick on 1",
    snare: "clean snare on 3",
    hats: "bright shuffle",
    perc: "shaker, conga",
    bass: "melodic bass, still heavy",
    melody: "bright guitar riff, horn stab, tropical synth",
    texture: "polished radio, still a riddim not a ballad",
    compactExtra: "snare on 3, tropical guitar, bright bass",
    intro: "guitar riff",
    verse: "island pocket, toast-ready, no vocals",
    hook: "horn stab, guitar full",
    brk: "percussion only",
    drop: "full island riddim",
    outro: "guitar delay",
    exclude: ["vocals", "singing", "toasting", "choir", "sad piano"],
    names: ["SUN 100", "RUM RIFF", "ISLAND 3", "PALM STAB"]
  },
  {
    id: "steppers",
    family: "dancehall",
    name: "Steppers / Rub-a-Dub",
    region: "Jamaica",
    era: "1979–1986",
    bpm: [80, 92],
    defaultBpm: 86,
    key: "Emin",
    drumIdentity: "steppers",
    genre: "rub-a-dub steppers instrumental riddim",
    mood: "driving, roots, hypnotic",
    kick: "four-on-the-floor-ish steppers kick, driving",
    snare: "snare on 2 and 4 or 3 depending on the bar, military-ish",
    hats: "straight 8ths",
    perc: "hi-hat opens, syndrum",
    bass: "walking heavy bass",
    melody: "organ, guitar skank",
    texture: "studio one warmth described as analog Jamaican mix, spring reverb",
    compactExtra: "steppers kick, organ, heavy bass",
    intro: "kick pattern alone",
    verse: "full steppers riddim",
    hook: "organ bubble",
    brk: "dub delay",
    drop: "drums back",
    outro: "spring reverb wash",
    exclude: ["vocals", "singing", "toasting", "choir", "trap"],
    names: ["STEP 86", "RUB DUB", "ORGAN BUBBLE", "KICK ROOTS"]
  },

  /* ───────── AFROBEATS ───────── */
  {
    id: "lagos-afro",
    family: "afro",
    name: "Lagos Afrobeats",
    region: "Lagos",
    era: "2018–2026",
    bpm: [98, 108],
    defaultBpm: 104,
    key: "Fmin",
    drumIdentity: "syncopated afrobeats",
    genre: "Nigerian afrobeats instrumental beat",
    mood: "groovy, warm, night-drive",
    kick: "syncopated kick, not four-on-the-floor, pocket on the 1 with offbeat pickups",
    snare: "crisp snare/clap on 2 and 4 with ghost notes, never dancehall-only-on-3",
    hats: "light hats plus constant shekere eighth-note pulse",
    perc: "talking drum fills, congas, shaker",
    bass: "warm round bass guitar in the pocket, melodic but locked",
    melody: "clean muted guitar on the upbeats, short melodic guitar hook",
    texture: "Lagos nightclub polish, percussion-forward, singer-ready space, no vocals",
    compactExtra: "shekere, talking drum, muted guitar, 104 BPM",
    intro: "shekere + muted guitar, bass enters",
    verse: "full afrobeats pocket, talking drum under, empty for a singer, generate no vocals",
    hook: "melodic guitar hook, percussion thicker, snare brighter",
    brk: "percussion and bass only, guitar drops",
    drop: "full groove returns, guitar hook repeats",
    outro: "shekere and guitar fade, no choir",
    exclude: ["vocals", "singing", "rapping", "choir", "toasting", "spoken word", "ad-libs", "log drum"],
    names: ["LAGOS 104", "SHEKE PULSE", "MUTED HOOK", "NIGHT 1AM"]
  },
  {
    id: "afro-fusion",
    family: "afro",
    name: "Afro-Fusion",
    region: "West Africa",
    era: "2020–2026",
    bpm: [96, 106],
    defaultBpm: 100,
    key: "Amin",
    drumIdentity: "mid-tempo afro-fusion",
    genre: "afro-fusion instrumental beat, West African pop",
    mood: "romantic, groovy, polished",
    kick: "round kick, lightly syncopated",
    snare: "soft clap on 2 and 4",
    hats: "silky hats, shekere bed",
    perc: "talking drum, light conga",
    bass: "deep resonant bass, slow-groove",
    melody: "lush keys, melodic electric guitar riff",
    texture: "streaming-ready, warm, not percussive-only",
    compactExtra: "melodic guitar, warm bass, shekere",
    intro: "guitar riff + pad",
    verse: "slow-groove afro pocket",
    hook: "guitar hook full, perc lifts",
    brk: "keys and bass",
    drop: "full fusion groove",
    outro: "guitar delay",
    exclude: ["vocals", "singing", "rapping", "choir", "trap hats", "harsh 808"],
    names: ["PALM 100", "SLOW GROOVE", "WARM RIFF", "FUSION 96"]
  },
  {
    id: "amapiano",
    family: "afro",
    name: "Amapiano",
    region: "South Africa",
    era: "2019–2026",
    bpm: [110, 115],
    defaultBpm: 112,
    key: "Gmin",
    drumIdentity: "amapiano log-drum groove",
    genre: "amapiano instrumental beat",
    mood: "hypnotic, deep, late-night Joburg",
    kick: "deep kick, unhurried, not four-on-the-floor house",
    snare: "soft snare/clap, laid-back",
    hats: "soft rolling shakers, not trap rolls",
    perc: "log drum as the lead percussion, piano stabs",
    bass: "deep log-drum bassline, the amapiano signature",
    melody: "slick piano chords, airy pads, no vocals",
    texture: "South African piano-house, spacious, hypnotic",
    compactExtra: "log drum, piano stabs, 112 BPM, shakers",
    intro: "piano chords, shaker",
    verse: "log drum groove, deep bass, shakers",
    hook: "piano more present, log drum busier",
    brk: "piano + shaker only",
    drop: "log drum returns full",
    outro: "piano fade, log drum stop",
    exclude: ["vocals", "singing", "rapping", "choir", "chants", "trap 808 slides", "talking drum"],
    names: ["LOG 112", "JOBURG KEYS", "PIANO DUST", "DEEP SHAKER"]
  },
  {
    id: "afro-house",
    family: "afro",
    name: "Afro House",
    region: "South Africa / Global",
    era: "2014–2026",
    bpm: [118, 124],
    defaultBpm: 120,
    key: "Dmin",
    drumIdentity: "four-on-the-floor afro house",
    genre: "afro house instrumental beat",
    mood: "uplifting, tribal, hypnotic",
    kick: "four-on-the-floor house kick",
    snare: "clap on 2 and 4",
    hats: "crisp house hats",
    perc: "organic African percussion, congas, shakers",
    bass: "warm house bass, sidechained",
    melody: "warm pads, piano stabs, no chants",
    texture: "club, organic-electronic, peak-time but warm",
    compactExtra: "4/4 kick, organic perc, warm bass",
    intro: "perc + filtered kick",
    verse: "full afro house groove",
    hook: "piano stab hook",
    brk: "perc breakdown",
    drop: "kick returns, bass full",
    outro: "filter out",
    exclude: ["vocals", "singing", "rapping", "choir", "tribal chants", "vocal chops"],
    names: ["FLOOR 120", "WARM PERC", "SA HOUSE", "PAD 122"]
  },
  {
    id: "highlife",
    family: "afro",
    name: "Highlife Groove",
    region: "Ghana / Nigeria",
    era: "1970s / modern",
    bpm: [108, 118],
    defaultBpm: 114,
    key: "Cmaj",
    drumIdentity: "highlife",
    genre: "highlife-influenced afrobeats instrumental beat",
    mood: "bright, joyful, guitar-led",
    kick: "bouncy kick, syncopated",
    snare: "snare on 2 and 4, light",
    hats: "ride and shaker",
    perc: "congas, clave-like timeline",
    bass: "melodic bass guitar, walking",
    melody: "bright guitar arpeggios, horn stabs, no vocals",
    texture: "live-band warmth, West African joy",
    compactExtra: "guitar arpeggios, congas, bright bass",
    intro: "guitar arpeggio",
    verse: "highlife pocket",
    hook: "horn stabs, guitars thicker",
    brk: "conga + bass",
    drop: "full highlife",
    outro: "guitar fade",
    exclude: ["vocals", "singing", "choir", "trap", "dark 808"],
    names: ["PALM WINE", "GOLD RIFF", "HORN 114", "ACCRA SUN"]
  },
  {
    id: "afro-trap",
    family: "afro",
    name: "Afro-Trap",
    region: "France / West Africa",
    era: "2016–2024",
    bpm: [100, 120],
    defaultBpm: 110,
    key: "Fmin",
    drumIdentity: "afro-trap",
    genre: "afro-trap instrumental beat",
    mood: "dark-groovy, street, modern",
    kick: "808 kick with afro syncopation",
    snare: "snare/clap hybrid, sometimes on 3, sometimes 2 and 4",
    hats: "trap rolls over afro shaker",
    perc: "African perc + trap perc",
    bass: "808 sub with afro bass rhythm",
    melody: "flute or kalimba-like pluck, minor",
    texture: "crossover, night, heavy low end",
    compactExtra: "808, afro perc, flute pluck",
    intro: "pluck + 808",
    verse: "afro-trap pocket",
    hook: "flute hook, hats roll",
    brk: "perc only",
    drop: "808 full",
    outro: "hard stop",
    exclude: ["vocals", "singing", "rapping", "choir"],
    names: ["FLUTE 110", "AFRO 808", "NIGHT PERC", "PLUCK TRAP"]
  },
  {
    id: "alte",
    family: "afro",
    name: "Alté",
    region: "Lagos",
    era: "2017–2026",
    bpm: [88, 108],
    defaultBpm: 98,
    key: "Emin",
    drumIdentity: "alté left-field afro",
    genre: "Nigerian alté instrumental beat",
    mood: "left-field, hazy, stylish",
    kick: "unusual kick placement, not straight afrobeats",
    snare: "light snare, sometimes rim",
    hats: "broken hat pattern",
    perc: "odd shakers, found-sound perc",
    bass: "synth bass, elastic",
    melody: "dreamy guitar, odd synth, indie-afro",
    texture: "DIY-luxe, alternative, not radio-afrobeats",
    compactExtra: "broken drums, dreamy guitar, Lagos alté",
    intro: "guitar wash",
    verse: "alté pocket, spacey",
    hook: "synth motif",
    brk: "ambient",
    drop: "drums return off-kilter",
    outro: "wash out",
    exclude: ["vocals", "singing", "choir", "generic afropop"],
    names: ["ALTÉ 98", "HAZY LAGOS", "BROKEN HAT", "INDIE AFRO"]
  },
  {
    id: "gqom",
    family: "afro",
    name: "Gqom",
    region: "Durban",
    era: "2013–2022",
    bpm: [124, 130],
    defaultBpm: 127,
    key: "Cmin",
    drumIdentity: "gqom",
    genre: "Durban gqom instrumental beat",
    mood: "dark, raw, hypnotic",
    kick: "huge broken kick pattern, not four-on-the-floor, the gqom kick",
    snare: "snare/clap in broken places, not house",
    hats: "minimal",
    perc: "synth screams as perc, industrial ticks",
    bass: "the kick is the bass, extra sub hits",
    melody: "almost none, dark atmosphere, sparse stabs",
    texture: "raw Durban taxi-rank energy, dark club",
    compactExtra: "broken gqom kick, dark, 127 BPM",
    intro: "atmosphere, kick teases",
    verse: "full gqom kick pattern, hypnotic",
    hook: "stab, kick denser",
    brk: "silence + sub",
    drop: "kick pattern slams",
    outro: "kick dies",
    exclude: ["vocals", "singing", "choir", "chants", "piano house", "log drum"],
    names: ["DURBAN 127", "BROKEN KICK", "TAXI RANK", "DARK GQOM"]
  },
  {
    id: "afro-rnb",
    family: "afro",
    name: "Afro-R&B",
    region: "Lagos / London",
    era: "2019–2026",
    bpm: [90, 102],
    defaultBpm: 96,
    key: "Dmin",
    drumIdentity: "afro-R&B",
    genre: "afro-R&B instrumental beat",
    mood: "sensual, smooth, modern",
    kick: "soft syncopated kick",
    snare: "soft snap on 2 and 4",
    hats: "silky, shekere quiet",
    perc: "talking drum very low",
    bass: "warm sub + bass guitar blend",
    melody: "Rhodes + muted guitar",
    texture: "bedroom-to-club, romantic",
    compactExtra: "Rhodes, muted guitar, soft afro drums",
    intro: "Rhodes",
    verse: "afro-R&B pocket",
    hook: "guitar lick",
    brk: "bass + keys",
    drop: "full groove",
    outro: "Rhodes fade",
    exclude: ["vocals", "singing", "choir", "harsh trap"],
    names: ["SILK AFRO", "RHODES 96", "SOFT LAGOS", "MUTED 90"]
  },
  {
    id: "fela-afrobeat",
    family: "afro",
    name: "Afrobeat (Fela-era)",
    region: "Lagos",
    era: "1970s",
    bpm: [100, 112],
    defaultBpm: 108,
    key: "Fmaj",
    drumIdentity: "classic afrobeat polyrhythm",
    genre: "1970s afrobeat instrumental, not afrobeats-pop",
    mood: "driving, political-heat, hypnotic",
    kick: "driving kick inside a polyrhythm",
    snare: "snare/rim in clave-adjacent pattern",
    hats: "shekere and hi-hat timeline, never stops",
    perc: "congas, shekere, talking drum, full percussion choir but no voices",
    bass: "hypnotic repeating bass riff",
    melody: "horn section stabs and riffs, jazz-funk guitar",
    texture: "live band, long jam, vintage warmth, instrumental",
    compactExtra: "horn riffs, polyrhythm, hypnotic bass",
    intro: "percussion timeline",
    verse: "full afrobeat jam, horns in punches",
    hook: "horn riff hook",
    brk: "percussion only",
    drop: "horns + bass riff return",
    outro: "percussion fade",
    exclude: ["vocals", "singing", "chanting", "choir", "modern trap", "log drum"],
    names: ["KALAKUTA", "HORN RIFF", "SHEKE 108", "BASS JAM"]
  },

  /* ───────── CLUB ───────── */
  {
    id: "dembow",
    family: "club",
    name: "Dembow / Reggaeton",
    region: "Caribbean / Latin",
    era: "2000s–2026",
    bpm: [88, 100],
    defaultBpm: 95,
    key: "Amin",
    drumIdentity: "dembow",
    genre: "dembow reggaeton instrumental beat",
    mood: "bouncy, nocturnal, club",
    kick: "kick on 1 and the and-of-2, the dembow kick",
    snare: "snare on 3, plus the dembow ghost",
    hats: "simple, some rolls in modern versions",
    perc: "guiro, timbale fills",
    bass: "deep bass, sometimes 808, always dembow rhythm",
    melody: "sparse dark synth or guitar, not busy",
    texture: "club, perreo, toast/rap-ready, no vocals",
    compactExtra: "dembow kick, snare on 3, deep bass",
    intro: "dembow drums filtered",
    verse: "full dembow pocket",
    hook: "synth stab, drums same",
    brk: "kick + bass",
    drop: "full dembow",
    outro: "drums stop on 1",
    exclude: ["vocals", "singing", "rapping", "choir", "toasting"],
    names: ["DEMBOW 95", "PERREO", "GUIRO SUB", "NIGHT 3"]
  },
  {
    id: "baile",
    family: "club",
    name: "Baile Funk",
    region: "Rio",
    era: "2000s–2026",
    bpm: [130, 150],
    defaultBpm: 140,
    key: "Cmin",
    drumIdentity: "baile funk / montagem",
    genre: "baile funk instrumental beat, Brazilian funk",
    mood: "raw, chaotic, dance",
    kick: "distorted kick, syncopated, the tamborzão feel",
    snare: "snare/clap in funk carioca pattern",
    hats: "minimal or chopped",
    perc: "tamborzao, chopped percussion",
    bass: "dirty bass, sometimes the kick",
    melody: "simple synth stab, montagem chops, no vocals",
    texture: "raw, street, loud, loop-based",
    compactExtra: "tamborzão kick, montagem, 140 BPM",
    intro: "stab loop",
    verse: "full baile pocket",
    hook: "stab denser",
    brk: "kick only",
    drop: "full funk",
    outro: "hard cut",
    exclude: ["vocals", "singing", "rapping", "choir", "funk carioca vocals", "MC"],
    names: ["TAMBOR 140", "RIO FUNK", "MONTAGEM", "DIRTY KICK"]
  },
  {
    id: "uk-garage",
    family: "club",
    name: "UK Garage",
    region: "London",
    era: "1998–2004 / revival",
    bpm: [128, 135],
    defaultBpm: 130,
    key: "Amin",
    drumIdentity: "2-step garage",
    genre: "UK garage 2-step instrumental beat",
    mood: "skippy, nocturnal, stylish",
    kick: "skippy 2-step kick, not four-on-the-floor",
    snare: "snare on 2 and 4 with shuffled extra snares",
    hats: "shuffled hats, the UKG skip",
    perc: "rim, bongo, shuffled",
    bass: "warm sub with reese or organ bass",
    melody: "organs, 2-step stabs, no vocals or vocal chops",
    texture: "London night bus, skippy, chrome",
    compactExtra: "2-step kick, shuffled snares, organ bass",
    intro: "shuffled hats + bass",
    verse: "full 2-step pocket",
    hook: "organ stab",
    brk: "bass + hats",
    drop: "full garage",
    outro: "filter",
    exclude: ["vocals", "singing", "choir", "vocal chops", "four-on-the-floor"],
    names: ["2STEP 130", "NIGHT BUS", "SKIP SNARE", "ORGAN SUB"]
  },
  {
    id: "uk-funky",
    family: "club",
    name: "UK Funky",
    region: "London",
    era: "2008–2012",
    bpm: [128, 132],
    defaultBpm: 130,
    key: "Fmin",
    drumIdentity: "UK funky",
    genre: "UK funky instrumental beat",
    mood: "percussive, dance, afro-london",
    kick: "funky syncopated kick around 130",
    snare: "claps in funky places",
    hats: "busy perc hats",
    perc: "African-leaning perc, cowbell, shakers",
    bass: "bouncy bassline",
    melody: "synth stabs, whistle-like synth no voice",
    texture: "London warehouse, percussive",
    compactExtra: "funky 130 kick, afro perc, bouncy bass",
    intro: "perc",
    verse: "UK funky pocket",
    hook: "stab hook",
    brk: "perc break",
    drop: "full funky",
    outro: "perc fade",
    exclude: ["vocals", "singing", "choir", "chants"],
    names: ["FUNKY 130", "COWBELL LDN", "PERC 128", "BOUNCE"]
  },
  {
    id: "soca",
    family: "club",
    name: "Soca",
    region: "Trinidad",
    era: "modern",
    bpm: [155, 170],
    defaultBpm: 160,
    key: "Cmaj",
    drumIdentity: "soca",
    genre: "soca instrumental beat",
    mood: "euphoric, carnival, fast",
    kick: "driving soca kick",
    snare: "snare/clap pattern, energetic",
    hats: "fast shakers",
    perc: "iron, conga, cowbell",
    bass: "bouncy bass",
    melody: "bright synth, horn-like stabs, no vocals",
    texture: "carnival, sunny, fast",
    compactExtra: "fast soca drums, iron perc, bright stabs",
    intro: "iron perc",
    verse: "full soca beat",
    hook: "synth hook",
    brk: "perc break",
    drop: "full carnival",
    outro: "stop",
    exclude: ["vocals", "singing", "choir", "slow"],
    names: ["FETE 160", "IRON 155", "CARNIVAL", "SUN BASS"]
  },
  {
    id: "kompa",
    family: "club",
    name: "Kompa",
    region: "Haiti",
    era: "modern",
    bpm: [88, 104],
    defaultBpm: 96,
    key: "Gmin",
    drumIdentity: "kompa",
    genre: "kompa instrumental beat",
    mood: "groovy, romantic, guitar-led",
    kick: "kompa kick, syncopated",
    snare: "snare in kompa pattern",
    hats: "steady, plus tanbou feel",
    perc: "Haitian drum colors, conga",
    bass: "melodic kompa bass",
    melody: "twinkling guitar, the kompa guitar, keys",
    texture: "smooth, dance, Caribbean",
    compactExtra: "kompa guitar, groovy bass, 96 BPM",
    intro: "guitar twinkle",
    verse: "kompa pocket",
    hook: "guitar hook",
    brk: "bass + perc",
    drop: "full kompa",
    outro: "guitar fade",
    exclude: ["vocals", "singing", "choir"],
    names: ["KONPA 96", "TWINKLE", "TANBOU", "SMOOTH AYITI"]
  },
  {
    id: "jersey",
    family: "club",
    name: "Jersey Club",
    region: "Newark",
    era: "2010s–2026",
    bpm: [130, 145],
    defaultBpm: 137,
    key: "Cmin",
    drumIdentity: "jersey club",
    genre: "jersey club instrumental beat",
    mood: "bouncy, chaotic, party",
    kick: "the jersey club kick pattern, bed-squeak-era kick, rapid",
    snare: "busy snare/clap chops",
    hats: "minimal, kick is the rhythm",
    perc: "chopped hits, no vocal chops",
    bass: "the kick carries bass",
    melody: "simple, chopped, instrumental only",
    texture: "raw club, loop, Newark",
    compactExtra: "jersey kick pattern, chopped drums, 137 BPM",
    intro: "kick tease",
    verse: "full jersey pattern",
    hook: "extra snare chops",
    brk: "kick only",
    drop: "full club",
    outro: "cut",
    exclude: ["vocals", "singing", "rapping", "choir", "vocal samples", "bed squeak vocals"],
    names: ["JERSEY 137", "KICK CHOP", "NEWARK", "CLUB BED"]
  },
  {
    id: "moombahton",
    family: "club",
    name: "Moombahton",
    region: "Global",
    era: "2010s",
    bpm: [105, 115],
    defaultBpm: 108,
    key: "Fmin",
    drumIdentity: "moombahton",
    genre: "moombahton instrumental beat",
    mood: "heavy, tropical, half-time house",
    kick: "reggaeton-ish kick at house-half-time",
    snare: "snare on 3",
    hats: "house hats slowed",
    perc: "tropical perc",
    bass: "heavy bass, Dutch-house growl without being dubstep",
    melody: "synth riff, tropical",
    texture: "festival, heavy, 108",
    compactExtra: "108 BPM, snare on 3, heavy tropical bass",
    intro: "perc + bass",
    verse: "moombahton pocket",
    hook: "synth riff",
    brk: "build without vocals",
    drop: "full 108 slam",
    outro: "filter",
    exclude: ["vocals", "singing", "choir"],
    names: ["MOOMB 108", "HEAVY 3", "TROP DROP", "HALF HOUSE"]
  },

  /* ───────── MORE ───────── */
  {
    id: "phonk",
    family: "more",
    name: "Drift Phonk",
    region: "Internet / Memphis",
    era: "2020–2024",
    bpm: [120, 145],
    defaultBpm: 130,
    key: "Emin",
    drumIdentity: "phonk",
    genre: "drift phonk instrumental beat",
    mood: "dark, aggressive, night-drive",
    kick: "heavy 808 kick",
    snare: "phonk snare, cowbell often instead of snare",
    hats: "triplet rolls",
    perc: "cowbell is the identity, Memphis",
    bass: "distorted 808, long decay",
    melody: "pitched-down choir-like synth, not real choir vocals, dark loop",
    texture: "vinyl degradation, drift, night",
    compactExtra: "cowbell, distorted 808, 130 BPM, no vocals",
    intro: "cowbell + pitched synth",
    verse: "full phonk pocket",
    hook: "808 meaner, cowbell hotter",
    brk: "synth only",
    drop: "full phonk",
    outro: "808 decay",
    exclude: ["vocals", "singing", "rapping", "real choir", "spoken word"],
    names: ["COWBELL 130", "DRIFT 808", "MEMPHIS NIGHT", "FUZZ LOOP"]
  },
  {
    id: "cloud",
    family: "more",
    name: "Cloud Rap",
    region: "Internet",
    era: "2012–2018",
    bpm: [130, 160],
    defaultBpm: 148,
    key: "Amin",
    drumIdentity: "cloud rap",
    genre: "cloud rap instrumental beat",
    mood: "hazy, ethereal, sad",
    kick: "soft kick, not punchy",
    snare: "snare on 3, washed",
    hats: "light, airy",
    perc: "almost none",
    bass: "soft 808",
    melody: "ethereal pads, pitched samples, no vocals",
    texture: "reverb cloud, dream, not aggressive",
    compactExtra: "hazy pads, soft 808, snare on 3",
    intro: "pad cloud",
    verse: "cloud pocket",
    hook: "sample-like synth, still no voice",
    brk: "pads",
    drop: "soft drums back",
    outro: "reverb",
    exclude: ["vocals", "singing", "rapping", "choir", "harsh 808"],
    names: ["CLOUD 148", "HAZE 808", "WASHED 3", "ETHERAL"]
  },
  {
    id: "grime",
    family: "more",
    name: "Grime",
    region: "East London",
    era: "2003–2010 / revival",
    bpm: [138, 142],
    defaultBpm: 140,
    key: "Cmin",
    drumIdentity: "grime",
    genre: "UK grime instrumental beat",
    mood: "cold, square, street",
    kick: "square kick, 140, syncopated",
    snare: "thin snare, distinctive grime placement",
    hats: "sparse, icy",
    perc: "old video-game perc, clicks",
    bass: "square / saw bass, not long 808 slides",
    melody: "ice synth stabs, 8-bit-ish, no vocals",
    texture: "cold, digital, pirate-radio",
    compactExtra: "140 BPM, square bass, icy stabs",
    intro: "stab",
    verse: "grime pocket, MC-ready, no vocals",
    hook: "stab hook",
    brk: "bass only",
    drop: "full 140",
    outro: "stop",
    exclude: ["vocals", "singing", "MCing", "choir", "US trap"],
    names: ["WILEY 140", "SQUARE BASS", "PIRATE", "ICE STAB"]
  },
  {
    id: "dnb",
    family: "more",
    name: "Drum & Bass",
    region: "UK",
    era: "modern",
    bpm: [170, 176],
    defaultBpm: 174,
    key: "F#min",
    drumIdentity: "rolling breakbeat",
    genre: "drum and bass instrumental beat",
    mood: "driving, dark-euphoric",
    kick: "punchy DnB kick inside the break",
    snare: "snare on the backbeat of the break, amen-style chops",
    hats: "fast, from the break",
    perc: "chopped break fills",
    bass: "deep sub + reese bass",
    melody: "pads, stabs, no vocals",
    texture: "rolling, club, 174",
    compactExtra: "rolling breaks, reese bass, 174 BPM",
    intro: "pad + filtered break",
    verse: "full rolling beat",
    hook: "reese opens",
    brk: "pads, breaks filtered",
    drop: "full 174 drop",
    outro: "break fade",
    exclude: ["vocals", "singing", "choir", "half-time trap"],
    names: ["REESE 174", "AMEN ROLL", "SUB 170", "DROP 174"]
  },
  {
    id: "house",
    family: "more",
    name: "Deep House",
    region: "Global",
    era: "modern",
    bpm: [118, 124],
    defaultBpm: 122,
    key: "Amin",
    drumIdentity: "four-on-the-floor",
    genre: "deep house instrumental beat",
    mood: "groovy, hypnotic, late-night",
    kick: "four-on-the-floor house kick",
    snare: "clap on 2 and 4",
    hats: "shimmering offbeat hats",
    perc: "shaker, conga",
    bass: "warm analog bass, sidechained",
    melody: "chords, rhodes, no vocals",
    texture: "club, warm, looping",
    compactExtra: "4/4 kick, warm bass, Rhodes, 122 BPM",
    intro: "filtered kick",
    verse: "full deep house",
    hook: "chord hook",
    brk: "perc + bass",
    drop: "kick full",
    outro: "filter down",
    exclude: ["vocals", "singing", "choir", "vocal chops"],
    names: ["DEEP 122", "OFFBEAT HAT", "WARM 4/4", "NIGHT KEYS"]
  },
  {
    id: "afro-drill",
    family: "more",
    name: "Afro-Drill",
    region: "UK / West Africa",
    era: "2021–2026",
    bpm: [138, 145],
    defaultBpm: 140,
    key: "Dmin",
    drumIdentity: "drill with afro perc",
    genre: "afro-drill instrumental beat",
    mood: "dark, groovy, street",
    kick: "drill kick, syncopated",
    snare: "UK drill snares plus afro ghost",
    hats: "drill rolls + shaker",
    perc: "shekere or conga under drill",
    bass: "sliding 808",
    melody: "afro guitar fragment or flute, minor",
    texture: "crossover, night",
    compactExtra: "sliding 808, afro perc, 140 BPM",
    intro: "guitar + 808",
    verse: "afro-drill pocket",
    hook: "flute/guitar hook",
    brk: "perc",
    drop: "full 140",
    outro: "stop",
    exclude: ["vocals", "singing", "rapping", "choir"],
    names: ["AFRO 140", "SLIDE SHEKE", "ENDS LAGOS", "DRILL PERC"]
  }
];
